from typing import Any

class Response:
    status_code: int
    def json(self) -> Any: ...
    def raise_for_status(self) -> None: ...

def get(*args: Any, **kwargs: Any) -> Response: ...
def post(*args: Any, **kwargs: Any) -> Response: ...
def put(*args: Any, **kwargs: Any) -> Response: ...

